grpc-server:
  port: ":5101"
  host: ""

database:
  host: "auth_service-db"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "userdb"

rabbitmq:
  queueName: "auth_health"
  host:
  port:
  user:
  password: