version: '3.8'

services:
  react-client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - graphql-server

  graphql-server:
    build: ./internal/services/graphql
    ports:
      - "4000:4000"
    depends_on:
      - auth_service
      - health_service
    networks:
      - microservices-network

  auth_service:
    build: ./internal/services/auth_service
    ports:
      - "5101:5101"
    depends_on:
      - auth_service-db
      - rabbitmq
    networks:
      - microservices-network
      - auth-network

  auth_service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - auth_service-db-data:/var/lib/postgresql/data
    networks:
      - auth-network

  health_service:
    build: ./internal/services/health_service
    ports:
      - "5102:5102"
    depends_on:
      - health_service-db
      - rabbitmq
    networks:
      - microservices-network
      - health-network

  health_service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthdb
    ports:
      - "5433:5432"
    volumes:
      - health_service-db-data:/var/lib/postgresql/data
    networks:
      - health-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  note_service:
    build: ./internal/services/note_service
    ports:
      - "5103:5103"
    depends_on:
      - note_service-db
    networks:
      - microservices-network
      - note-network

  note_service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notedb
    ports:
      - "5434:5432"
    volumes:
      - note_service-db-data:/var/lib/postgresql/data
    networks:
      - note-network

  crew_service:
    build: ./internal/services/crew_service
    ports:
      - "5104:5104"
    depends_on:
      - crew_service-db
    networks:
      - microservices-network
      - crew-network

  crew_service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crewdb
    ports:
      - "5435:5432"
    volumes:
      - crew_service-db-data:/var/lib/postgresql/data
    networks:
      - crew-network

volumes:
  auth_service-db-data:
  health_service-db-data:
  note_service-db-data:
  crew_service-db-data:
  rabbitmq_data:

networks:
  microservices-network:
  auth-network:
  note-network:
  crew-network:
  health-network:
    driver: bridge