CREATE TABLE IF NOT EXISTS users_health_data (
    userId VARCHAR(100) PRIMARY KEY,
    age INT DEFAULT 0,
    height FLOAT DEFAULT 0.0,
    weight FLOAT DEFAULT 0.0,
    pulse INT DEFAULT 0,
    pressure VARCHAR(30) DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);