// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: protos/graph_note/graph_note.proto

package graph_note

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddVisitRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DoctorName string `protobuf:"bytes,2,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	VisitDate  string `protobuf:"bytes,3,opt,name=visitDate,proto3" json:"visitDate,omitempty"`
}

func (x *AddVisitRecordRequest) Reset() {
	*x = AddVisitRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_note_graph_note_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVisitRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVisitRecordRequest) ProtoMessage() {}

func (x *AddVisitRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_note_graph_note_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVisitRecordRequest.ProtoReflect.Descriptor instead.
func (*AddVisitRecordRequest) Descriptor() ([]byte, []int) {
	return file_protos_graph_note_graph_note_proto_rawDescGZIP(), []int{0}
}

func (x *AddVisitRecordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddVisitRecordRequest) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *AddVisitRecordRequest) GetVisitDate() string {
	if x != nil {
		return x.VisitDate
	}
	return ""
}

type AddVisitRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddVisitRecordResponse) Reset() {
	*x = AddVisitRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_note_graph_note_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVisitRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVisitRecordResponse) ProtoMessage() {}

func (x *AddVisitRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_note_graph_note_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVisitRecordResponse.ProtoReflect.Descriptor instead.
func (*AddVisitRecordResponse) Descriptor() ([]byte, []int) {
	return file_protos_graph_note_graph_note_proto_rawDescGZIP(), []int{1}
}

func (x *AddVisitRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserVisitRecordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetUserVisitRecordsRequest) Reset() {
	*x = GetUserVisitRecordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_note_graph_note_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserVisitRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVisitRecordsRequest) ProtoMessage() {}

func (x *GetUserVisitRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_note_graph_note_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVisitRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetUserVisitRecordsRequest) Descriptor() ([]byte, []int) {
	return file_protos_graph_note_graph_note_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserVisitRecordsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserVisitRecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VisitRecords []*VisitRecord `protobuf:"bytes,1,rep,name=visitRecords,proto3" json:"visitRecords,omitempty"`
}

func (x *GetUserVisitRecordsResponse) Reset() {
	*x = GetUserVisitRecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_note_graph_note_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserVisitRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVisitRecordsResponse) ProtoMessage() {}

func (x *GetUserVisitRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_note_graph_note_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVisitRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetUserVisitRecordsResponse) Descriptor() ([]byte, []int) {
	return file_protos_graph_note_graph_note_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserVisitRecordsResponse) GetVisitRecords() []*VisitRecord {
	if x != nil {
		return x.VisitRecords
	}
	return nil
}

type VisitRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordNumber   string `protobuf:"bytes,1,opt,name=recordNumber,proto3" json:"recordNumber,omitempty"`
	DoctorName     string `protobuf:"bytes,2,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	Specialization string `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	VisitDate      string `protobuf:"bytes,4,opt,name=visitDate,proto3" json:"visitDate,omitempty"`
}

func (x *VisitRecord) Reset() {
	*x = VisitRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_note_graph_note_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitRecord) ProtoMessage() {}

func (x *VisitRecord) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_note_graph_note_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitRecord.ProtoReflect.Descriptor instead.
func (*VisitRecord) Descriptor() ([]byte, []int) {
	return file_protos_graph_note_graph_note_proto_rawDescGZIP(), []int{4}
}

func (x *VisitRecord) GetRecordNumber() string {
	if x != nil {
		return x.RecordNumber
	}
	return ""
}

func (x *VisitRecord) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *VisitRecord) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *VisitRecord) GetVisitDate() string {
	if x != nil {
		return x.VisitDate
	}
	return ""
}

var File_protos_graph_note_graph_note_proto protoreflect.FileDescriptor

var file_protos_graph_note_graph_note_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e,
	0x6f, 0x74, 0x65, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x74, 0x65,
	0x22, 0x6d, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74, 0x44, 0x61, 0x74, 0x65, 0x22,
	0x32, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x34, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69,
	0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x76, 0x69, 0x73, 0x69,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x56, 0x69, 0x73, 0x69,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0c, 0x76, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x73, 0x69, 0x74, 0x44, 0x61, 0x74, 0x65, 0x32,
	0xcf, 0x01, 0x0a, 0x0c, 0x56, 0x69, 0x73, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x57, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x2e,
	0x41, 0x64, 0x64, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f,
	0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x26, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x73,
	0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x6f,
	0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_graph_note_graph_note_proto_rawDescOnce sync.Once
	file_protos_graph_note_graph_note_proto_rawDescData = file_protos_graph_note_graph_note_proto_rawDesc
)

func file_protos_graph_note_graph_note_proto_rawDescGZIP() []byte {
	file_protos_graph_note_graph_note_proto_rawDescOnce.Do(func() {
		file_protos_graph_note_graph_note_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_graph_note_graph_note_proto_rawDescData)
	})
	return file_protos_graph_note_graph_note_proto_rawDescData
}

var file_protos_graph_note_graph_note_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_graph_note_graph_note_proto_goTypes = []any{
	(*AddVisitRecordRequest)(nil),       // 0: graph_note.AddVisitRecordRequest
	(*AddVisitRecordResponse)(nil),      // 1: graph_note.AddVisitRecordResponse
	(*GetUserVisitRecordsRequest)(nil),  // 2: graph_note.GetUserVisitRecordsRequest
	(*GetUserVisitRecordsResponse)(nil), // 3: graph_note.GetUserVisitRecordsResponse
	(*VisitRecord)(nil),                 // 4: graph_note.VisitRecord
}
var file_protos_graph_note_graph_note_proto_depIdxs = []int32{
	4, // 0: graph_note.GetUserVisitRecordsResponse.visitRecords:type_name -> graph_note.VisitRecord
	0, // 1: graph_note.VisitService.AddVisitRecord:input_type -> graph_note.AddVisitRecordRequest
	2, // 2: graph_note.VisitService.GetUserVisitRecords:input_type -> graph_note.GetUserVisitRecordsRequest
	1, // 3: graph_note.VisitService.AddVisitRecord:output_type -> graph_note.AddVisitRecordResponse
	3, // 4: graph_note.VisitService.GetUserVisitRecords:output_type -> graph_note.GetUserVisitRecordsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_graph_note_graph_note_proto_init() }
func file_protos_graph_note_graph_note_proto_init() {
	if File_protos_graph_note_graph_note_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_graph_note_graph_note_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddVisitRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_graph_note_graph_note_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddVisitRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_graph_note_graph_note_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserVisitRecordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_graph_note_graph_note_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserVisitRecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_graph_note_graph_note_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*VisitRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_graph_note_graph_note_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_graph_note_graph_note_proto_goTypes,
		DependencyIndexes: file_protos_graph_note_graph_note_proto_depIdxs,
		MessageInfos:      file_protos_graph_note_graph_note_proto_msgTypes,
	}.Build()
	File_protos_graph_note_graph_note_proto = out.File
	file_protos_graph_note_graph_note_proto_rawDesc = nil
	file_protos_graph_note_graph_note_proto_goTypes = nil
	file_protos_graph_note_graph_note_proto_depIdxs = nil
}
