// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: protos/graph_crew/graph_crew.proto

package graph_crew

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDoctorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDoctorsRequest) Reset() {
	*x = GetDoctorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_crew_graph_crew_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDoctorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorsRequest) ProtoMessage() {}

func (x *GetDoctorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_crew_graph_crew_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorsRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorsRequest) Descriptor() ([]byte, []int) {
	return file_protos_graph_crew_graph_crew_proto_rawDescGZIP(), []int{0}
}

type GetDoctorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Doctors []*Doctor `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
}

func (x *GetDoctorsResponse) Reset() {
	*x = GetDoctorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_crew_graph_crew_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDoctorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorsResponse) ProtoMessage() {}

func (x *GetDoctorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_crew_graph_crew_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorsResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorsResponse) Descriptor() ([]byte, []int) {
	return file_protos_graph_crew_graph_crew_proto_rawDescGZIP(), []int{1}
}

func (x *GetDoctorsResponse) GetDoctors() []*Doctor {
	if x != nil {
		return x.Doctors
	}
	return nil
}

type Doctor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId        string `protobuf:"bytes,1,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	DoctorName      string `protobuf:"bytes,2,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	Specialization  string `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	ExperienceYears int32  `protobuf:"varint,4,opt,name=experienceYears,proto3" json:"experienceYears,omitempty"`
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_graph_crew_graph_crew_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_crew_graph_crew_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_protos_graph_crew_graph_crew_proto_rawDescGZIP(), []int{2}
}

func (x *Doctor) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *Doctor) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *Doctor) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *Doctor) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

var File_protos_graph_crew_graph_crew_proto protoreflect.FileDescriptor

var file_protos_graph_crew_graph_crew_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x63,
	0x72, 0x65, 0x77, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x72, 0x65, 0x77, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x72, 0x65, 0x77,
	0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x72, 0x65, 0x77, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x07, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x06, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x59, 0x65, 0x61, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x59, 0x65, 0x61,
	0x72, 0x73, 0x32, 0x5a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12,
	0x1d, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x72, 0x65, 0x77, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x72, 0x65, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x72, 0x65, 0x77, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_graph_crew_graph_crew_proto_rawDescOnce sync.Once
	file_protos_graph_crew_graph_crew_proto_rawDescData = file_protos_graph_crew_graph_crew_proto_rawDesc
)

func file_protos_graph_crew_graph_crew_proto_rawDescGZIP() []byte {
	file_protos_graph_crew_graph_crew_proto_rawDescOnce.Do(func() {
		file_protos_graph_crew_graph_crew_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_graph_crew_graph_crew_proto_rawDescData)
	})
	return file_protos_graph_crew_graph_crew_proto_rawDescData
}

var file_protos_graph_crew_graph_crew_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_graph_crew_graph_crew_proto_goTypes = []any{
	(*GetDoctorsRequest)(nil),  // 0: graph_crew.GetDoctorsRequest
	(*GetDoctorsResponse)(nil), // 1: graph_crew.GetDoctorsResponse
	(*Doctor)(nil),             // 2: graph_crew.Doctor
}
var file_protos_graph_crew_graph_crew_proto_depIdxs = []int32{
	2, // 0: graph_crew.GetDoctorsResponse.doctors:type_name -> graph_crew.Doctor
	0, // 1: graph_crew.CrewService.GetDoctors:input_type -> graph_crew.GetDoctorsRequest
	1, // 2: graph_crew.CrewService.GetDoctors:output_type -> graph_crew.GetDoctorsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_graph_crew_graph_crew_proto_init() }
func file_protos_graph_crew_graph_crew_proto_init() {
	if File_protos_graph_crew_graph_crew_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_graph_crew_graph_crew_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetDoctorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_graph_crew_graph_crew_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetDoctorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_graph_crew_graph_crew_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Doctor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_graph_crew_graph_crew_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_graph_crew_graph_crew_proto_goTypes,
		DependencyIndexes: file_protos_graph_crew_graph_crew_proto_depIdxs,
		MessageInfos:      file_protos_graph_crew_graph_crew_proto_msgTypes,
	}.Build()
	File_protos_graph_crew_graph_crew_proto = out.File
	file_protos_graph_crew_graph_crew_proto_rawDesc = nil
	file_protos_graph_crew_graph_crew_proto_goTypes = nil
	file_protos_graph_crew_graph_crew_proto_depIdxs = nil
}
