// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: protos/graph_crew/graph_crew.proto

package graph_crew

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrewService_GetDoctors_FullMethodName = "/graph_crew.CrewService/GetDoctors"
)

// CrewServiceClient is the client API for CrewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrewServiceClient interface {
	GetDoctors(ctx context.Context, in *GetDoctorsRequest, opts ...grpc.CallOption) (*GetDoctorsResponse, error)
}

type crewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrewServiceClient(cc grpc.ClientConnInterface) CrewServiceClient {
	return &crewServiceClient{cc}
}

func (c *crewServiceClient) GetDoctors(ctx context.Context, in *GetDoctorsRequest, opts ...grpc.CallOption) (*GetDoctorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorsResponse)
	err := c.cc.Invoke(ctx, CrewService_GetDoctors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrewServiceServer is the server API for CrewService service.
// All implementations must embed UnimplementedCrewServiceServer
// for forward compatibility.
type CrewServiceServer interface {
	GetDoctors(context.Context, *GetDoctorsRequest) (*GetDoctorsResponse, error)
	mustEmbedUnimplementedCrewServiceServer()
}

// UnimplementedCrewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrewServiceServer struct{}

func (UnimplementedCrewServiceServer) GetDoctors(context.Context, *GetDoctorsRequest) (*GetDoctorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDoctors not implemented")
}
func (UnimplementedCrewServiceServer) mustEmbedUnimplementedCrewServiceServer() {}
func (UnimplementedCrewServiceServer) testEmbeddedByValue()                     {}

// UnsafeCrewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrewServiceServer will
// result in compilation errors.
type UnsafeCrewServiceServer interface {
	mustEmbedUnimplementedCrewServiceServer()
}

func RegisterCrewServiceServer(s grpc.ServiceRegistrar, srv CrewServiceServer) {
	// If the following call pancis, it indicates UnimplementedCrewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrewService_ServiceDesc, srv)
}

func _CrewService_GetDoctors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).GetDoctors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_GetDoctors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).GetDoctors(ctx, req.(*GetDoctorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrewService_ServiceDesc is the grpc.ServiceDesc for CrewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graph_crew.CrewService",
	HandlerType: (*CrewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDoctors",
			Handler:    _CrewService_GetDoctors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/graph_crew/graph_crew.proto",
}
