package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/peygy/medapp/internal/pkg/grpc"
	pb "github.com/peygy/medapp/internal/pkg/protos/graph_auth"
	"github.com/peygy/medapp/internal/services/graphql/graph/model"
)

func findServiceIndex(services []grpc.GrpcService, name string) int {
	for i, service := range services {
		if service.Name == name {
			return i
		}
	}
	return -1
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input model.User) (*model.AuthPayload, error) {
	authConnIdx := findServiceIndex(r.GrpcServices, "auth_service")
	client := pb.NewSignUpServiceClient(r.GrpcServices[authConnIdx].Conn)

	signUpResponce, err := client.SignUp(ctx, &pb.SignUpRequest{
		Username: input.Username,
		Password: input.Password,
	})
	if err != nil {
		fmt.Print(err)
		return nil, fmt.Errorf("graphql: could not sign up new user: %v", err)
	}

	return &model.AuthPayload{
		UserID: signUpResponce.GetUserId(),
		Role:   signUpResponce.GetRole(),
	}, nil
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input model.User) (*model.AuthPayload, error) {
	authConnIdx := findServiceIndex(r.GrpcServices, "auth_service")
	client := pb.NewSignUpServiceClient(r.GrpcServices[authConnIdx].Conn)

	signUpResponce, err := client.SignUp(ctx, &pb.SignUpRequest{
		Username: input.Username,
		Password: input.Password,
	})
	if err != nil {
		fmt.Print(err)
		return nil, fmt.Errorf("graphql: could not sign in new user: %v", err)
	}

	return &model.AuthPayload{
		UserID: signUpResponce.GetUserId(),
		Role:   signUpResponce.GetRole(),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
